### Delete for username: AlexisAllGood

DELETE http://localhost:3003/api/blogs/64148eb164e9b4152ebf5a1d
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hIiwiaWQiOiI2NDE0ODM4Y2QwM2E1MjJiOTc4MjJlMWUiLCJpYXQiOjE2NzkwNjgxMDF9.BVJl12c2LcdgVZO4wUptm98QLGOd5_KGj0tFBQxmNCI

###



