POST http://localhost:3003/api/blogs 
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hIiwiaWQiOiI2NDE0ODM4Y2QwM2E1MjJiOTc4MjJlMWUiLCJpYXQiOjE2NzkwNjYxMzZ9.g4kdrmnYwopS2XPp3zgAaMXpRe_tgriBK3Su4DLFPMc

{
   "title": "Final post with Middleware user extractor",
    "author": "Alex",
    "url": "wwww.lel.com",
    "likes": "55"
}