GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs 
content-type: application/json

{
    "title": "How to test with supertest and jest",
    "author": "Me",
    "url": "wwww.example.com",
    "likes": "65",
}
