POST http://localhost:3001/api/blogs 
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik5vcm1hIiwiaWQiOiI2NDY3OTk1YTc0NWIzOTgyOTFiMmQ2NzgiLCJpYXQiOjE2ODQ1MTEwNzEsImV4cCI6MTY4NDUxNDY3MX0.DB939v6nfDHtb_Lp8HsXYndVFTof1VRRjQPE-3GWVqw

{
   "title": "PUT test 1",
    "author": "Alex",
    "url": "wwww.lel.com",
    "likes": "55"
}